### ISSUE TITLE
Error on example script

### ISSUE THREAD

**Issue by LordTlasT** [ugorsahin/ChatGPT_Selenium#2]
Hello, you're projects seems awesome!
Unfortunately, I cannot get it to work.
I am trying to run the example:
```python
from handler import Handler

chatgpt = Handler("spasswd", "spasswd")
answer = chatgpt.interact("Hellow, how are you today")
print(answer)
```

I am using python 3.10.10 and Linux.

This is the error I get:
```
Traceback (most recent call last):
  File "$HOME/ChatGPT_Selenium/main.py", line 3, in <module>
    chatgpt = Handler("spasswd", "spasswd")
  File "$HOME/ChatGPT_Selenium/handler.py", line 94, in __init__
    self.browser = uc.Chrome(options=options)
  File "$HOME/ChatGPT_Selenium/env/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1722, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
```

**Comment by ugorsahin** [comment]
The traceback seems uncomplete, can you share the rest of the traceback?

**Comment by LordTlasT** [comment]
I am confused, this is what my terminal looks like

> (env)  $ *python main.py*
```
Traceback (most recent call last):
  File "/home/aluc/src/ChatGPT_Selenium/main.py", line 3, in <module>
    chatgpt = Handler("spasswd", "spasswd")
  File "/home/aluc/src/ChatGPT_Selenium/handler.py", line 94, in __init__
    self.browser = uc.Chrome(options=options)
  File "/home/aluc/src/ChatGPT_Selenium/env/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1722, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ugorsahin** [comment]
Hey, no worries. Thanks for the input. I am happy to hear that it is functioning now.

 Also, headless was working until the point they updated stuff. I will take a look into that at some point.

Wish you a great day!
